---
apiVersion: v1
kind: Secret
metadata:
  name: config-addvol
  namespace: kube-system
stringData:
  SCW_ACCESS_KEY: SCWxxx
  SCW_DEFAULT_ORGANIZATION_ID: xxx-xx-xxxxx
  SCW_SECRET_KEY: xxx-xx-xxxxx
  SCW_DEFAULT_PROJECT_ID: xxx-xx-xxxxx
  VOL_SIZE: "20G"
  PREFIX: "addvol"
  IOPS: "15000"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: addvol
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app-sys: addvol
  template:
    metadata:
      labels:
        app-sys: addvol
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      initContainers:
      - name: addvol
        image: ghcr.io/n-arno/kapsule-host-vol-addvol:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: config-addvol
      containers:
      - name: pause
        image: registry.k8s.io/pause:latest
        imagePullPolicy: IfNotPresent
